### ISSUE TITLE
Network info doesn't appear after migration to GitHub Repo

### ISSUE THREAD

**Issue by zdenotim** [zdenotim/PiZet#1]
## `Network Info

Traceback (most recent call last):
  File "./PiZet_a0_4.py", line 353, in <module>
    net_info()
  File "./PiZet_a0_4.py", line 150, in net_info
    open('int_info_' + i, 'w').write(out)
IOError: [Errno 13] Permission denied: 'int_info_nrtap'`

-[I need to update path to temp files created during script performance]

**Comment by zdenotim** [comment]
Issue resolved use sudo or grant privileges to user.

```
> XYZ@XYZ:~/PiZet/PiZet $ sudo ./PiZet_a0_4.py -n
> Hostname: XYZ
> 
> Networking Info
> ---------------
> Interface  MAC                IP              RX         TX        
> nrtap      9e:e7:28:c8:37:11  172.16.0.2       0.00 MiB   0.00 MiB
> wlan0      b8:27:eb:1f:07:e3  192.168.0.14    47.79 MiB   0.06 MiB
> eth0       b8:27:eb:4a:52:b6  192.168.3.14    20.01 MiB   6.01 MiB
> 
> Last Refresh: Fri Jun 10 15:06:05 2016
> 
> Alpha version of PiZet (2016a0.4)
> Code made by zdenotim (c) 2016
> --- 0.029897 seconds ---
> 
```
